name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - 'publish/*'
  # # pull_request event is required only for autolabeler
  # pull_request:
  #   # Only following types are handled by the action, but one can default to all as well
  #   types: [opened, reopened, synchronize]
  # # pull_request_target event is required for autolabeler to support PRs from forks
  # # pull_request_target:
  # #   types: [opened, reopened, synchronize]

permissions:
  contents: read

jobs:
  update_release_draft:
    permissions:
      # write permission is required to create a github release
      contents: write
      # write permission is required for autolabeler
      # otherwise, read permission is required at least
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Version Getter
        id: version
        run: | # Use a multi-line string for complex commands
          # Get the version tag
          tag=$(echo "${{ github.ref_name }}" | sed 's/^publish\///')
          
          # Generate the timestamp in the desired format
          timestamp=$(TZ='America/Los_Angeles' date +%Y.%m.%e_%k.%M)
          
          # Write the combined version string to the GITHUB_OUTPUT
          echo "tag=$tag" >> $GITHUB_OUTPUT
          echo "version=v$timestamp" >> $GITHUB_OUTPUT
        shell: bash
      # Drafts your next Release notes as Pull Requests are merged into "master"
      - uses: ncipollo/release-action@v1
        with:
          name: "${{steps.version.outputs.tag}} Release ${{steps.version.outputs.version}}"
          tag: "${{steps.version.outputs.tag}}-${{steps.version.outputs.version}}"
          skipIfReleaseExists: true
          makeLatest: true
          generateReleaseNotes: true
          token: ${{ secrets.PAT }}
          
      # - uses: release-drafter/release-drafter@v5
      #   # (Optional) specify config name to use, relative to .github/. Default: release-drafter.yml
      #   with:
      #       name: "${{steps.version.outputs.tag}} Release ${{steps.version.outputs.version}}"
      #       tag: "${{steps.version.outputs.tag}}-${{steps.version.outputs.version}}"
      #   #   config-name: my-config.yml
      #   #   disable-autolabeler: true
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}